### PR TITLE
'Custom' connection type for the connection generator

### PR DESCRIPTION
**Pull request by lukeburpee**
### Problem
Currently, the connection generator is restricted to service database connections, using only adapters currently supported by the service generator. This places an arbitrary restriction on the creation of custom services that depend on external apis, currently unsupported databases, etc.

By adding a 'custom' option to the connection generator, additional connections can be created and stored within the feathers-gen-spec file, using the same methods as those already supported by the generator.

### CODE REVIEW

**Comment by lukeburpee** [comment]
I misspoken when I used the word adapter. This pull request only relates to the connection generator and would not be used by the service generator.

Essentially, the request allows you to create a custom connection client and store a reference to that client in the feathers-gen-spec file along with you're sql, mongoose, etc. clients.

Say I want to build a custom service that manages docker containers and I need a docker client. This request would allow me to generate a custom docker client file and store the reference the docker client in the feathers-gen-spec. 

I figured this would be a good way to store references to custom connection clients (elasticsearch, couch, etc.), without making the connection client list insanely long.

**Comment by NickBolles** [comment]
I'm not fully understanding this. But for example I have an email notification module that I keep in src/lib/notifier.ts and I import in the code into app.ts or wherever I need it. 

I'm wondering if having something like that built into cli+ to abstract some of the logic into self contained files and make it easier to encapsulate parts of code and as an added bonus make it easier to unit test.

**Comment by eddyystop** [comment]
You could require modules and then use them in app.configure by adding custom code in the appropriate places. So is the issue that you cannot add the module being referred to?

My comments are always influenced by remembering you desire to hydrate apps with generate all. Is this part if the issue? You can always include the middle to be required in the folder containing the feathers-gen-doecs file.

What am I missing here?

**Comment by eddyystop** [comment]
If the above makes sense
- What is amanifest-friendly name for the property containing the list in feathers-specs-gen?
- Won't you eventually want to include other types of files? Images for example would not be text files.

**Comment by eddyystop** [comment]
Reopening to more easily keep track of this discussion.

**Comment by lukeburpee** [comment]
So basically:

1. Generate a file with a default file name (like custom or blank js/ts) that includes insertion points

2. Have the developer update the filename and add the file to the feathers-gen-spec so that the file is regenerated on generate all

3. have generate all only generate the file when it doesn't exist

If so, problem solved.

Hmmm, hard to think of a property name that won't be confused for other "custom" properties here...maybe "additions" or "supplemental"?

As for other file types, I see two primary places they may come into play:

- **testing**: First, you could pull any non text files you need remotely or store them via travis cache. Second, after tests have run and passed, they no longer need to be included in your application.

- **user interface**: It all depends on your choice of architecture. (I have a few more ideas concerning separation of concerns/choice of architecture I'd like to add to the generator, but I don't want to scare you too much. I mean, wouldn't it be cool if you could decide between a single app, app-per-service, or service cluster approach? Kind of waiting to see what you guys do with feathers-auth-management before diving in too deep) At the very least, I intend to separate my UI from my services in a monorepo, so all non-text files associated with the UI can be stored separately.

**Comment by lukeburpee** [comment]
You might also be sending various file types among services, but that wouldn't impact the implementation of the services themselves. They would still be constructed via text.

**Comment by eddyystop** [comment]
I don't see the custom module needing defined `// !code` insertion points. `generate codelist` would get the module name from feathers-gen-specs and copy that whole module into feathers-gen-code.

It seems convenient to copy the module under a hardcoded insertion point named, say, `whole_module` so such code has the same "form" as the rest of feathers-gen-code. There is also a method in code-fragments.js which would return the module code given the module name and `whole_module`.

I wouldn't want to use a property in feathers-gen-specs named `dependencies` as that likely cause confusion.

What about adding the following? Do we **really** need to distinguish between production and development?
```js
requiresCustomResources: {
  production: {
    js: ['src/services/serviceName/foo.ts' ], // path from root of app, globs not allowed (for now?)
  },
  development: { // i.e. testing
    js: ['testing/bar.ts' ]
  }
}
```

**Comment by eddyystop** [comment]
Don't expect `authentication-local-management` soon. I'm burned out on it.

It easy to conceive big plans. It takes man-years to implement them. I wouldn't implement any features which do not have a huge following. This is why Knex, Onjective, etc. are not supported. Their maintenance would not be worth it.

**Comment by lukeburpee** [comment]
requiresCustomResources sounds good, and I agree that we don't really need both production and development. I think making multi-file tests a generator concern would definitely be pushing it.

And as long as the custom code retains the form of code list, it works, so including by module name would be fine. Currently the generated json code list uses the template tags as keys for their in-file input location, but, for custom modules, I'll set it up to create one big array of text lines.

First things first, probably best to lock down the current codelist generator updates before adding any further updates, unless you think its better to just update the whole thing at one time.

**Comment by eddyystop** [comment]
I'm waiting on j2L4e to review https://github.com/feathers-plus/generator-feathers-plus/pull/171 . I did leave 1 comment for you though.

Once that is merged, I can make more sense out of https://github.com/feathers-plus/generator-feathers-plus/pull/175 .


If you add `// !code` in an added custom module, the code wrapped within that would be stored by code-fragments.js as that scans all .js and .ts files in the app. However I think its too hacky to depend on that and it just works with .js and .ts files. So I think its better to explicitly read and include the custom modules.

There is an issue though. The presently generated codelist does not specify the module's .js or .ts suffix. The custom modules would have to specify it. The method for returning code fragments should work as needed if you call it with with the full file name.

**Comment by eddyystop** [comment]
How about this, so it makes sense for JSON, etc.?

```js
requiresCustomResources: {
  text: ['src/services/serviceName/foo.ts' ], // path from root of app, globs not allowed (for now?)
}
```

**Comment by lukeburpee** [comment]
How about 'textFiles'? That ways there's no potential confusion over whether to include a filepath or raw text.

And shouldn't be hard to ensure file extensions are preserved if we iterate over the custom text files separately from the files containing code fragments. Seems like the best way would be to pass the spec to the code-fragments.js refreshFragments function via the spec.js setPath function. Then, iterate over the text files and add the array to the refreshFragments function glob ignore list. This way we can avoid iterating over custom modules twice (assuming the modules are js/ts. otherwise, refreshCodeFragments will ignore the files anyways). Plus, by passing to refreshCodeFragments, we leave the door open for blobs down the road.

**Comment by eddyystop** [comment]
Ok textFikes.

Generators/writing/index.js needs to create the added files as it writes all files.

Generators/codelist/index.js copies the files into feathers-gen-code.

Code-fragments.js sole responsibility is to cache code from insertion points and return code asked for.

**Comment by eddyystop** [comment]
If you want I  can update writing/index.js if you update contents of feathers.gen.code.

**Comment by lukeburpee** [comment]
@eddyystop sounds good to me

**Comment by eddyystop** [comment]
feathers-gen-specs.json
```json
{
  "options": {
    "ver": "1.0.0",
    "inspectConflicts": false,
    "semicolons": true,
    "freeze": [],
    "ts": false
  },
  "app": {
    "environmentsAllowingSeedData": "",
    "seedData": false,
    "name": "yy",
    "description": "Project yy",
    "src": "src",
    "packager": "npm@>= 3.0.0",
    "providers": [
      "rest",
      "socketio"
    ]
  },
  "services": {},
  "hooks": {},
  "requiredCustomResources": {
    "files": {
      "text": [
        "src/custom-js.js"
      ]
    }
  }
}
```

feathers-gen-code.js
```js
// !module src/index.**

// !code: listening
console.log('listening');
// !end

// !module requiredCustomResources

// !code: src/custom-js.js
console.log('customJs.js line 1');

console.log('customJs.js line 2');
console.log('customJs.js line 3');
// !end
```

`generate all` creates src/custom-js.js if it does not already exist.

Published as f+/cli 0.7.77  ujsing generator v0.6.75 .

You'll handle using requiredCustomResources.files.text to **replace/add** the following on `generate codelist`
```js
// !module requiredCustomResources

// !code: src/custom-js.js
console.log('customJs.js line 1');

console.log('customJs.js line 2');
console.log('customJs.js line 3');
// !end
```

**But we have an outstanding issue with https://github.com/feathers-plus/generator-feathers-plus/pull/171 before you can start on updating codelist.**

**Pull request closed without merging**
