### PR TITLE
Updates to allow custom resources in codelist

### PR DESCRIPTION
**Pull request by lukeburpee**
- Pass spec to fragment refresh
- Parse custom resources found in spec and add to code fragments
- Codelist formatting logic moved from codelist generator to code-fragments.js via formatCodelist, flattenCodelist, and flattenCodelistModule utils

### CODE REVIEW

**Comment by lukeburpee** [comment]
See #167 for context

**Comment by eddyystop** [comment]
Can't seem to find option for review comments. So here they are. I'll post when I'm ended.

Shouldn't 
```js
  if (codelist === {} ) {
    if (logger) {
      logger();
      logger(yellow.bold(`No custom application code found.`));
      logger();
      return;
    } else {
      return;
    }
  }
``
be something like
```js
  if (Object.keys(codelist).length === 0 ) {
    if (logger) {
      logger();
      logger(yellow.bold(`No custom application code found.`));
      logger();
    }
    return;
  }
```

**Comment by eddyystop** [comment]
```js
async function extractProject (specs) {
  const resources = (((specs.requiredCustomResources || {}).files || {}).text || []);
  try {	  try {
    const files = glob.sync(	    const files = glob.sync(
      `${destinationRoot}/**/*.{js,ts}`, { ignore: [	      `${destinationRoot}/**/*.{js,ts}`, { ignore: [
          `${destinationRoot}/**/node_modules/**`,	          `${destinationRoot}/**/node_modules/**`,
          `${destinationRoot}/public/**`	          `${destinationRoot}/public/**`,
          ...resources
        ]}	        ]}
    );	    );
```
This stops code-fragments.js from scanning the files in requiredCustomResources for code insertion points. But those modules cannot have "valid" code insertion points by definition and its not our responsibility to try to compensate for user errors.

The points is refreshCodeFragments' signature has been changed in order to pass `specs` to extractProject and `specs` has been included in its calls. The code would be simpler if specs was not a parameter for extractProject .

Or what am I missing here?

**Comment by eddyystop** [comment]
I'm going to merge the PR as is.

**Comment by eddyystop** [comment]
Published as f+/cli v0.7.79 using generator v0.6.77

**Pull request merged**
