### PR TITLE
Refactor 4

### PR DESCRIPTION
**Pull request by eddyystop**

### CODE REVIEW

**Comment by NickBolles** [comment]
@eddyystop all of these refactor PRs rely on the one before them right? If so this isn't the recommended way to do this type of thing. It should all be one PR or you should create the PR branch off of the remote master, not off of the other PR's branch.

**Comment by blackholegalaxy** [comment]
Maybe @eddyystop wanna do a final PR afterward with the entire refactor?

**Comment by eddyystop** [comment]
It'll be fine. I'm worried about just a large refactor.

**Comment by NickBolles** [comment]
@eddyystop exactly why it should be broken up. If it's not possible (the PRs depend on each other) then it can be done in one PR. But your last PR is going to be equal to one single PR with all of them. So choosing one way or the other is best. Doing it in the middle is just wasted work.

**Pull request merged**
