### PR TITLE
Updates to codelist generator to allow codelist file output

### PR DESCRIPTION
**Pull request by lukeburpee**
### Summary

Currently, the codelist generator only has the ability to print the custom code output to the console. This pull request gives the codelist generator the ability to output a feathers-gen-code file in js/ts, json, and txt formats, while maintaining the print to console as the generator default.

### Issues

No open issues

### Related Pull Requests

Test updates have been completed for this request and will be supplied in a separate pull request.

### CODE REVIEW

**Comment by eddyystop** [comment]
@lukeburpee I'm confused by this PR. It seems to do much more than changing the codelist generator.
- It makes changes to tslint.
- It introduces a nodemon.json file and I haven't found where that occurs.
- It unexpectedly adds a dev:seed script to package.json.

I feel a separate PR is needed for each individual change. I can't get a handle on all these changes being made at once, and I'm not confident the merged code will run properly.

**Comment by eddyystop** [comment]
Hmmm .. I now see a lot of these changes are being carried over from https://github.com/feathers-plus/generator-feathers-plus/pull/171

**Comment by eddyystop** [comment]
Could you remind me again what's the benefit in not just copying the folder with all the app files?

**Comment by lukeburpee** [comment]
Because it allows the developer to encapsulate all custom application code within a serializable format and regenerate the entire application, if necessary.

So the question then becomes, why store a single file json/text file and regenerate the entire application when you could just store the pre-generated application files? 

This assumes that the entire application and all its dependencies will be regenerated on feathers-plus generate all, when, in actuality, _the only code regenerated is the code that differs from the current application and the only dependencies installed are those not previously installed._ 

This means the developer can cache a pre-generated base application template, and use the template to reduce the generation time for new applications. Going even further, the base application template stored by the developer can be customized and these customizations can be extracted and stored. You could then cache multiple base application templates for use in different scenarios. (i.e. a mongo base application template and a sequelize base application template)

There are enumerable use cases for this features, but one of the clearest is that _it significantly reduces the complexity of creating **a feathers application service**_.

How about this: after we incorporate these codelist generator updates, I'll create an example application that highlights the new codelist features. 

Sometimes it's just easier to show than it is to tell.

**Comment by lukeburpee** [comment]
Closing to account for custom resource updates. New pull request to follow.

**Pull request closed without merging**
