### PR TITLE
Update Guide with Typescript module alias setup

### PR DESCRIPTION
**Pull request by heralight**
Update Guide documentation with Typescript module alias setup with ts-node.

Also update the generator template with this feature could be awesome!

Thank you!

### Summary

(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))

- [ ] Tell us about the problem your pull request is solving.
- [ ] Are there any open issues that are related to this?
- [ ] Is this PR dependent on PRs in other repos?

If so, please mention them to keep the conversations linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).

Thanks for contributing to Feathers! :heart:

### CODE REVIEW

**Comment by eddyystop** [comment]
@j2L4e ^^^

**Comment by j2L4e** [comment]
I think just mapping src/ to `@` would be a good way to catch all cases. Thats how vue-cli sets it up. 
You'd get paths ist like `@/services/comments/...`. In general this is a great idea to add.

I'll be back in town tomorrow night.

**Comment by eddyystop** [comment]
Do we agree that in tsconfig.json we add

```js
    "baseUrl": ".",                           /* Base directory to resolve non-absolute module names. */
    "paths": {                                /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
      "@/*": ["src/*"]
    },
``
This works for user-generated subfolders of src/ out-of-the-box.

**Comment by j2L4e** [comment]
yes :+1:

**Comment by eddyystop** [comment]
@heralight comments?

**Comment by heralight** [comment]
yes ! very good! thx

**Comment by eddyystop** [comment]
@heralight Do you want to change your PR?

**Comment by eddyystop** [comment]
Thanks for this.

**Pull request merged**
