### PR TITLE
Expose mongodb promise as variable

### PR DESCRIPTION
**Pull request by marshallswain**
This is a baby step towards fixing https://github.com/feathers-plus/generator-feathers-plus/issues/230

It exposes the promise in a variable so we can use the magic comments to work around the bug in that issue.

### CODE REVIEW

**Comment by eddyystop** [comment]
Would you mind changing the `const` to `let` so the generator's standard of using `let` so custom code can mutate such variables?

**Comment by marshallswain** [comment]
Done

**Comment by eddyystop** [comment]
Published as cli+ 0.8.3 which runs generator v0.8.3

**Comment by eddyystop** [comment]
Published as cli+ 0.8.3 which runs generator v0.8.3

**Pull request merged**
