### PR TITLE
Njb/fix tests on windows

### PR DESCRIPTION
**Pull request by NickBolles**
### Summary
The tests were using hard coded directory delimitors and were failing on windows because the files would be created with a CRLF instead of LF line ending. I tried to keep the comparison and just escape the values in the output so that you could tell, but it proved hard to escape the value while still printing the output correctly. 

I also added a diff output to make it simple to see what changed, instead of just that the whole file changed.

### CODE REVIEW

**Comment by NickBolles** [comment]
Here's an example of the diff view. Also, how can I get this test to pass? isn't the secret generated each time the app starts?

image

**Comment by eddyystop** [comment]
On my phone atm. The test runner passes a parameter to the called generator. That is used to optionally make the secret a fixed value.

**Comment by NickBolles** [comment]
alright, the issue was a hard coded check for `/tmp` instead of checking for the `require("os").tmpDir()` Fixed, and all tests are working on windows now, with the added bonus of diffing

**Comment by eddyystop** [comment]
Thanks! Especially since I had just sat down with my first coffee of the day to look into this.

**Comment by eddyystop** [comment]
Interesting to see that require('colors') adds to the String prototype.

**Comment by eddyystop** [comment]
@NickBolles I'm getting this error running the tests on Ubuntu
```txt

  generators-writing.test.js
    scaffolding.test
Using generator version 0.6.69
Source scan took 0s 118ms

      2 change specs {"app":{"providers":["primus"]}}
Using generator version 0.6.69
Source scan took 0s 154ms

      3 change specs {"app":{"providers":["rest"]}}
Using generator version 0.6.69
Source scan took 0s 153ms

      4 change specs {"app":{"providers":["rest","socketio"]}}
Using generator version 0.6.69
Source scan took 0s 248ms

      5 "generate all" with {"confirmation":true}
Using generator version 0.6.69
Source scan took 0s 155ms

... comparing code
>getFileNames /home/johnsz/shared/repos/feathers-plus/generator-feathers-plus/test-expands/scaffolding.test-expected
>getFileNames /tmp/3ae297093e66bcdff810fcab607adbee07ab8fd9
<EOL DIFF>cross-env NODE_ENV=test<EOL DIFF>cross-env NODE_ENV=test<EOL DIFF>      1) writes code expected

  6 passing (19s)
  1 failing

  1) generators-writing.test.js
       scaffolding.test
         writes code expected:

      AssertionError [ERR_ASSERTION]: Unexpected contents for file /tmp/3ae297093e66bcdff810fcab607adbee07ab8fd9/package.json
      + expected - actual

      -false
      +true
      
      at compare (test/z-generators-writing.test.js:1364:3)
      at actualPaths.paths.forEach.actualPath (test/z-generators-writing.test.js:1315:5)
      at Array.forEach (<anonymous>)
      at compareCode (test/z-generators-writing.test.js:1314:21)
      at runNextGenerator.then.dir (test/z-generators-writing.test.js:1123:19)
```

**Comment by eddyystop** [comment]
Expected was
```json
  "scripts": {
    "test": "npm run eslint && npm run mocha",
    "test:all": "npm run eslint && NODE_ENV=test npm run mocha",
    "eslint": "eslint src1/. test/. --config .eslintrc.json",
    "dev": "nodemon src1/",
    "dev:seed": "nodemon src1/ --seed",
    "start": "node src1/",
    "start:seed": "NODE_ENV=test node src/ --seed",
    "mocha": "mocha test/ --recursive --exit --timeout 10000"
  }
```
Actual was
```json
  "scripts": {
    "test": "npm run eslint && npm run mocha",
    "test:all": "npm run eslint && cross-env NODE_ENV= npm run mocha",
    "eslint": "eslint src1/. test/. --config .eslintrc.json",
    "dev": "nodemon src1/",
    "dev:seed": "nodemon src1/ --seed",
    "start": "node src1/",
    "start:seed": "cross-env NODE_ENV= node src/ --seed",
    "mocha": "mocha test/ --recursive --exit --timeout 10000"
  }
```
The resulting diff is not informative
```txt
<EOL DIFF>cross-env NODE_ENV=test<EOL DIFF>cross-env NODE_ENV=test<EOL DIFF>  
```
Perhaps we should have the mocha diff displayed as well?

**Comment by eddyystop** [comment]
I'll start changing tests with errors.

**Comment by eddyystop** [comment]
The actual was missing NODE_ENV=test. https://github.com/feathers-plus/generator-feathers-plus/pull/137 fixes this.

**Comment by NickBolles** [comment]
This is really weird
```
<EOL DIFF>cross-env NODE_ENV=test<EOL DIFF>cross-env NODE_ENV=test<EOL DIFF>  
```

I couldn't figure out a good way to display the end of line difference while keeping the line breaks, or not adding extra line breaks. If we can then we can just show the line break characters in the diff, which is very clean.

**Comment by eddyystop** [comment]
I think between the diff and mocha we can find what's different.

**Comment by eddyystop** [comment]
cli+ v0.7.72 published using generator v0.6.70

**Pull request merged**
