### PR TITLE
correctly import Knex

### PR DESCRIPTION
**Pull request by NickBolles**
### Summary
#122 

I'm not able to get the tests running, possibly because I'm on windows. Could somone test it for me? I'll try to on my linux machine if not

### CODE REVIEW

**Comment by eddyystop** [comment]
Yeoman's queuing subsystem has problems with win10 plus node10. Yeoman has not responded in 10 days to the issue I posted.

Are you running the generator with node10 and git bash? Or are you using mode 8? It reportedly hangs with PowerShell or command.exe.

**Comment by eddyystop** [comment]
Each generator test consists of 2 folders. Say xxx-copy and xxx-exoected. The test copies xxx-copy to a temp folder; runs generate all on it, sometimes runs other generate commands. It then does a string compare of the resulting temp folder to xxx-expected.

It stops at the first discrepancy.

What you posted is the mocha diff between the actalual and expected file. Above that diff is displayed the whole actual file.

The idea us to review the differences and if they are acceptable manually change xxx-expected to reflect the change.

Then you run the tests again to find the next diff. You can avoid returning tests which work in test/z-writing (?). At the end if the array listing the tests are 2 statements setting start and end test names to bill. Change those to select the test range.

**Comment by NickBolles** [comment]
Yea. I get most of that. But what I don't understand I guess is that what I posted is equal if I copy it into kdiff. Maybe theres a line ending difference??

I can try restricting the tests to the ones I need and report back

**Comment by eddyystop** [comment]
The endings in the target folders would be Linux LF not Window CRLF

**Comment by lukeburpee** [comment]
@NickBolles I was running into this problem with the tslint.json file yesterday and it turned out that I had added an extra space to the end of a few of rules. Once I deleted the extra spaces, the tests passed.

**Comment by j2L4e** [comment]
@NickBolles This is a weird issue, indeed! 
i have the tests running, mind if I just merge your PR and push the fixed tests myself?

**Comment by NickBolles** [comment]
@eddyystop sorry for ignoring half of your response earlier... I'm using node 9 I believe to avoid the yeoman issue. Also if your interested strapi has a few issues listed about the same hangup that might help? see https://github.com/strapi/strapi/issues/1927

@j2L4e that's fine by me. 

I will follow up with another PR to fix running the tests on windows. There are a few issues with hard coding / as the path delim and others. Your changes look good! Thank you!

**Comment by eddyystop** [comment]
Published as cli+ 0.7.71 which run generator v0.6.69. Thanks!

**Pull request merged**
