### PR TITLE
Handle copying enums to mongoose schema

### PR DESCRIPTION
**Pull request by marshallswain**
This allows properties with enums in the Feathers schema to be copied correctly to the Mongoose schema.

### CODE REVIEW

**Comment by eddyystop** [comment]
I believe correct JSON-schema syntax is for `items` to be an array:
```js
    roles: {
      type: 'array',
      items: [{
        type: 'string',
        enum: [ 'admin' ]
      }]
    },
```

**Comment by j2L4e** [comment]
Both seem to validate against the JSON-schema schemas if https://www.jsonschemavalidator.net/ does its job right.

**Comment by eddyystop** [comment]
I refactored the tests, moving out the expansion folders. I added `enum` to Mongoose and added your tests.

Published in f+/cli v0.4.22 using generator v0.2.28.

**Comment by eddyystop** [comment]
@j2L4e Thanks for that info. The generator assumes `items` is an array when type `array`.  I'll have to revisit this.

**Comment by eddyystop** [comment]
`items` as object is considered to be a 1-element array.

Published in f+/cli v0.4.23 using generator v0.2.29.

**Pull request closed without merging**
