### PR TITLE
Add code block for provider options

### PR DESCRIPTION
**Pull request by NickBolles**
### Summary
Adds code block so that you can add options to an authentication provider such as Verifier

### Other Information
I'm still working on getting the tests running, and I can  work on sometime in the next couple days. So this could be considered WIP.

### CODE REVIEW

**Comment by eddyystop** [comment]
+1

**Comment by NickBolles** [comment]
@eddyystop The tests are passing now

**Comment by eddyystop** [comment]
cli+ v0.7.72 published using generator v0.6.70

**Comment by NickBolles** [comment]
@eddyystop I just realized an issue with this, but I'm not sure how you'd like to handle it.

Basically we need a comma after Strategy in order to add properties to the object
image


would doing something like this be better?
image

**Comment by eddyystop** [comment]
Use a trailing commas e.g. ```Strategy" Auth0Strategy,```. First 1 type of standard, second the generator does it all the time so it doesn't have to track if a prop is the last one in the object.

**Comment by NickBolles** [comment]
@eddyystop Sounds good, PR submitted

**Pull request merged**
