### PR TITLE
Typescript sequelize fix

### PR DESCRIPTION
**Pull request by lukeburpee**
Fix for issue #169

### CODE REVIEW

**Comment by eddyystop** [comment]
Thanks a bunch.

@j2L4e ^^^

**Comment by eddyystop** [comment]
https://github.com/feathers-plus/generator-feathers-plus/pull/175 and https://github.com/feathers-plus/generator-feathers-plus/pull/176 are waiting on this PR

**Comment by eddyystop** [comment]
In 1fda3fe:
- feathersjs/generator-feathers uses `oldSetup.apply`. I prefer staying as source compatible with the original cli as possible. I don't understand why you changed it to `oldSetup.call`.

**Comment by lukeburpee** [comment]
@eddyystop because the call method takes an any[] type, while apply takes an [any?] type (call accepts an argument list (a la ...args) while apply accepts a single array of arguments). Therefore, the call method accepts the args rest operator while the apply method does not, To fix the issue arguments would have to be passed into the function in a different way or the args rest operator would have to be converted into a compatible type. 

Went with the simplest solution under the circumstances, but if the goal is maintaining source compatibility with feathers cli, I can figure out a way to parse the rest operator for ingestion by the apply method (second simplest fix). I'd have to dig a little further into the args passed to the adapter before messing with the function's rest operator input, but that could work too.

**Comment by eddyystop** [comment]
Thanks for the explaination. The change makes sense.

**Comment by lukeburpee** [comment]
The oldSetup function still receives arguments as it expects to receive them, the only difference being that apply allows you to pass the arguments as an array without enumerating the actual argument values.

Basically, oldSetup.call(this, ...args) equals oldSetup.apply(this, args), but you can't pass the spread args to call unless you're working with ES6 (which the generator does not).

Doesn't the oldSetup function take the app and path as its arguments (Application and string types)? Why not enumerate those instead of passing args as the input? Passing the rest operator muddies the waters here, especially considering the setup function passes additional arguments not required by the oldSetup function.

**Comment by lukeburpee** [comment]
@eddyystop yep, that should work, so just have to add the spread operator to args in the update and tests, and everything this should be good to go.

**Comment by lukeburpee** [comment]
closing and replacing with #182

**Comment by eddyystop** [comment]
Are we dropping the changes no involving `oldSetup.appy(...)`?

**Pull request closed without merging**
