### PR TITLE
Improve json schema export to mongoose

### PR DESCRIPTION
**Pull request by superdevofficial**
### Summary

Currently, when you export a service, some attributes in JSON-Schema are not exported into Mongoose Schema, ex: ref, minLength... 
This PR :
* Allow additionnal attributes (like minLength, min, ref)
* Format date is exported as Date type
* Array are exported as array of type or array of subschema

### Example
Source JSON Schema :
```js
  // Fields in the model.
  properties: {
    // !code: schema_properties
    id:        { type: 'ID' },
    parentId:  { type: 'ID', ref: 'User' },
    friendIds: {
            type: 'array',
            items: { type: 'ID', ref: 'User' },
            default: []
    },
    tags: { type: 'array', items: { type: 'string'} },
    email:     { minLength: 8, maxLength: 40, faker: 'internet.email' },
    firstName: { minLength: 2, maxLength: 15, faker: 'name.firstName' },
    lastName:  { minLength: 2, maxLength: 30, faker: 'name.lastName' },
    password:  { faker: { exp: 'ctx.hashPassword("superdev")' } },
    roleId:    { type: 'ID', faker: { fk: 'roles:random' } },
    image: {
        type: 'object',
        properties: {
            thumbnailPath: { type: 'string' },
            fullsizePath: { type: 'string' },
            updatedAt: { type: 'string', format:'date-time', default: Date.now },
        },
    }
```

Result : 
```js
let moduleExports = merge({},
  // !<DEFAULT> code: model
  {
    parentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User"
    },
    friendIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User"
      }
    ],
    tags: [
      String
    ],
    email: {
      type: String,
      minLength: 8,
      maxLength: 40,
      required: true,
      unique: true
    },
    firstName: {
      type: String,
      minLength: 2,
      maxLength: 15
    },
    lastName: {
      type: String,
      minLength: 2,
      maxLength: 30
    },
    password: String,
    roleId: mongoose.Schema.Types.ObjectId,
    image: {
      thumbnailPath: String,
      fullsizePath: String,
      updatedAt: {
        type: Date,
        default: Date.now
      }
    }
  },
  // !end
  // !code: moduleExports // !end
);
```

### CODE REVIEW

**Comment by eddyystop** [comment]
@marshallswain Could you please review this?

@superdevofficial Once Marshall looks at this, I'll ask you to update the tests in test/service-specs-to-mongoose.test.js

**Comment by marshallswain** [comment]
Looks good.  Awesome contribution!

**Comment by eddyystop** [comment]
@superdevofficial could you add a few tests in test/service-specs-to-mongoose.test.js ?

You'll want to skip test/z-generators-writing.test.js as that'll run tests which fail. I'll update the code targets for those tests myself.

**Comment by superdevofficial** [comment]
> @superdevofficial could you add a few tests in test/service-specs-to-mongoose.test.js ?
Ok I'm working on it !

**Comment by superdevofficial** [comment]
I added and updated tests into file `test/service-specs-to-mongoose.test.js`.

**Comment by eddyystop** [comment]
Perhaps you only ran mocha for test/service-specs-to-mongoose.test.js. They all need to run successfully except test/z-generators-writing.test.js.

Right now test/json-schema/marshall-app.test.js is failing:
```text
  1) marshall-app.test.js
       correctly converts schema to targets:

      mongooseSchema wrong
      + expected - actual

       {
      -  "emails": [
      -    {
      -      "email": [Function]
      -      "type": [Function]
      -    }
      -  ]
      +  "emails": []
         "name": {
           "required": true
           "type": [Function]
         }
         "notes": [Function]
      -  "phones": [
      -    {
      -      "number": [Function]
      -      "type": [Function]
      -    }
      -  ]
      +  "phones": []
         "primaryContact": [Function]
       }
      
      at Object.keys.forEach.name (test/helpers/json-schema-runner.js:58:12)
      at Array.forEach (<anonymous>)
      at jsonSchemaRunner (test/helpers/json-schema-runner.js:39:31)
      at Context.it (test/json-schema/marshall-app.test.js:3456:5)

```

**Comment by eddyystop** [comment]
Published final result as f+/cli v0.8.8 which uses generator v0.8.8

**Comment by eddyystop** [comment]
This PR has caused some issues https://github.com/feathers-plus/generator-feathers-plus/issues/246

**Comment by eddyystop** [comment]
Fixed via https://github.com/feathers-plus/generator-feathers-plus/issues/246 and https://github.com/feathers-plus/generator-feathers-plus/pull/252

Published f+/cli v0.8.9 which uses generator v0.8.9

**Pull request merged**
